config/routes.rb
Project1::Application.routes.draw do
  get "comments/new"
  get "sessions/new"

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy, :vote]
  resources :comments, :only => [:create, :destroy]
  resources :votes, :only => [:create]

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/microposts', :to => 'microposts#new'
  match '/comments', :to => 'comments#new'
  match '/votes', :to => 'microposts#vote'

  get "pages/home"
  get "users/new"
  get "microposts/new"

  root :to => 'pages#home'

end

app/views/layouts/_header.html.erb
<header>
  <%= link_to root_path %>
  <nav >
    <ul>
              <li><%= link_to "Home", root_path %></li>
              <% if signed_in? %>
              <li><%=link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li><%=link_to "Users", users_path %></li>

              <% end %>
              <% if signed_in? %>
              <li><%= link_to "Sign Out", signout_path %>
              <% else %>
              <li><%= link_to "Sign In", signin_path %></li>
              <% end %>
    </ul>

    </nav>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
        <head>
                <title><%= title %></title>
                <%= csrf_meta_tags %>
                <%= render 'layouts/header' %>
                <%= javascript_include_tag :defaults %>
                <%= javascript_include_tag :jquery %>
                <%= javascript_include_tag :rails %>
                <%= javascript_include_tag :application %>
                <!--[if lt IE 9]>
                <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
                <![endif]-->
                <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
                <%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
                <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
                 <%= stylesheet_link_tag 'custom', :media => 'screen' %>

         </head>
         <body>
                 <div class="container">
                         <section class="round">
                         <% if signed_in? %>
                                <%= render 'shared/user_info' %>
                         <% end %>
                         <% flash.each do |key, value| %>
                                 <div class="flash <%= key %>"><%= value %></div>
                         <% end %>
                         <%= yield %>
                         </section>
                 </div>

         </body>
</html>